require "capistrano/ci/version"
require "capistrano/ci/clients/base"
require "capistrano/ci/clients/travis"
require "capistrano/ci/clients/travis_pro"
require "capistrano/ci/clients/circle"
require "capistrano/ci/client"
